package com.example.util

import com.example.data.model.Language

object AppStrings {
    fun get(key: String, lang: Language): String {
        val entry = stringMap[key] ?: return key
        return when (lang) {
            Language.HINDI -> entry.hi
            Language.MARATHI -> entry.mr
            Language.ENGLISH -> entry.en
        }
    }

    private data class Trans(val hi: String, val mr: String, val en: String)

    private val stringMap = mapOf(
        "app_name" to Trans("कबाड़ीवाला", "कबाडीवाला", "KabadiWala"),
        "tagline" to Trans("बेचो सही। रिसाइकल सही।", "विका योग्य. रिसायकल योग्य.", "Becho Sahi. Recycle Sahi."),
        "sub_tagline" to Trans("कबाड़ी से फॉर्मल रिसाइक्लिंग तक", "कबाडी ते फॉर्मल रिसायकलिंग पर्यंत", "From Scrap to Formal Recycling"),
        "choose_lang" to Trans("अपनी भाषा चुनें", "तुमची भाषा निवडा", "Choose your language"),
        "welcome" to Trans("नमस्ते 👋", "नमस्ते 👋", "Namaste 👋"),
        "what_to_recycle" to Trans("आज क्या रिसाइकल करना है?", "आज काय रिसायकल करायचे आहे?", "What to recycle today?"),
        "new_lot" to Trans("नया लॉट बनाएं", "नवीन लॉट तयार करा", "Create New Lot"),
        "today_rates" to Trans("आज के रेट्स", "आजचे दर", "Today's Rates"),
        "find_recyclers" to Trans("रिसाइक्लर ढूंढें", "रिसायकलर शोधा", "Find Recyclers"),
        "my_transactions" to Trans("मेरे व्यवहार", "माझे व्यवहार", "My Transactions"),
        "safety_tips" to Trans("सुरक्षा सुझाव", "सुरक्षा सूचना", "Safety Tips"),
        "today_earnings" to Trans("आज की कमाई", "आजची कमाई", "Today's Earnings"),
        "pending_payment" to Trans("बाकी भुगतान", "थकबाकी पेमेंट", "Pending Payment"),
        "lots_sold" to Trans("बेचे गए लॉट", "विकलेले लॉट्स", "Lots Sold"),
        "recent_activity" to Trans("हालिया व्यवहार", "अलीकडील व्यवहार", "Recent Activity"),
        "take_photo" to Trans("मटेरियल की फोटो लें", "मटेरियलचा फोटो घ्या", "Take Material Photo"),
        "camera" to Trans("कैमरा से लें", "कॅमेराने घ्या", "Take Photo"),
        "gallery" to Trans("गैलरी से चुनें", "गॅलरीतून निवडा", "Choose from Gallery"),
        "ai_identify" to Trans("AI से पहचानें", "AI द्वारे ओळखा", "Identify with AI"),
        "ai_detected" to Trans("संभावित मटेरियल:", "संभाव्य मटेरियल:", "Likely Material:"),
        "confidence" to Trans("विश्वास:", "विश्वास:", "Confidence:"),
        "select_category" to Trans("मटेरियल की श्रेणी चुनें", "मटेरियलचा प्रकार निवडा", "Select Category"),
        "approx_weight" to Trans("अनुमानित वजन (किलो)", "अंदाजे वजन (किलो)", "Approximate Weight (kg)"),
        "condition" to Trans("हालत (कंडीशन)", "स्थिती", "Condition"),
        "source" to Trans("स्रोत (कहाँ से मिला)", "स्रोत (कुठून मिळाले)", "Source"),
        "see_price" to Trans("प्राइस देखें", "किंमत पहा", "Check Price"),
        "estimated_value" to Trans("अनुमानित मूल्य", "अंदाजे मूल्य", "Estimated Value"),
        "approx_rate" to Trans("अनुमानित दर:", "अंदाजे दर:", "Approximate Rate:"),
        "price_disclaimer" to Trans("अनुमानित बाज़ार मूल्य। रिसाइक्लर की जाँच के बाद अंतिम भाव तय होगा।", "अंदाजे बाजार भाव. तपासणीनंतर अंतिम किंमत ठरेल.", "Estimated market value. Final price may vary after recycler inspection."),
        "listen_price" to Trans("प्राइस सुनें 🔊", "किंमत ऐका 🔊", "Listen Price 🔊"),
        "listen_rates" to Trans("रेट्स सुनें 🔊", "दर ऐका 🔊", "Listen Rates 🔊"),
        "price_trend" to Trans("मूल्य रुझान (Price Trend)", "किंमतीचा कल", "Price Trend"),
        "increasing" to Trans("बढ़ रहा है 📈", "वाढत आहे 📈", "Increasing 📈"),
        "authorized_recyclers" to Trans("अधिकृत रिसाइक्लर", "अधिकृत रिसायकलर", "Authorized Recyclers"),
        "best_match" to Trans("सबसे उत्तम विकल्प 🥇", "सर्वोत्तम पर्याय 🥇", "Best Match 🥇"),
        "alternative" to Trans("दूसरा विकल्प 🥈", "पर्यायी पर्याय 🥈", "Alternative 🥈"),
        "pickup_available" to Trans("पिकअप उपलब्ध है 🚚", "पिकअप उपलब्ध आहे 🚚", "Pickup Available 🚚"),
        "pickup_unavailable" to Trans("पिकअप नहीं है ✕", "पिकअप नाही ✕", "Pickup Unavailable ✕"),
        "authorized" to Trans("अधिकृत (Authorized) 🟢", "अधिकृत (Authorized) 🟢", "Authorized 🟢"),
        "select_this_recycler" to Trans("इस रिसाइक्लर को चुनें", "हा रिसायकलर निवडा", "Select Recycler"),
        "confirm_lot" to Trans("लॉट कन्फर्म करें", "लॉट निश्चित करा", "Confirm Lot"),
        "handover_timeline" to Trans("हैंडओवर टाइमलाइन", "हस्तांतरण टाइमलाइन", "Handover Timeline"),
        "payment_method" to Trans("भुगतान का तरीका", "पेमेंट पद्धत", "Payment Method"),
        "cash" to Trans("नकद (Cash) 💵", "रोख (Cash) 💵", "Cash 💵"),
        "digital" to Trans("डिजिटल / UPI 📱", "डिजिटल / UPI 📱", "Digital Payment 📱"),
        "status_paid" to Trans("भुगतान हो गया 🟢", "पेमेंट झाले 🟢", "Paid 🟢"),
        "status_pending" to Trans("बाकी (Pending) 🟠", "प्रलंबित 🟠", "Pending 🟠"),
        "receipt_title" to Trans("डिजिटल हैंडओवर रसीद", "डिजिटल हस्तांतरण पावती", "Digital Handover Receipt"),
        "offline_mode" to Trans("ऑफलाइन मोड 🟠", "ऑफलाइन मोड 🟠", "Offline Mode 🟠"),
        "syncing" to Trans("डेटा सिंक हो रहा है... ☁️", "डेटा सिंक होत आहे... ☁️", "Syncing data... ☁️"),
        "synced" to Trans("सारा डेटा सिंक है ✓", "सर्व डेटा सिंक आहे ✓", "All data synced ✓"),
        "safety_title" to Trans("सुरक्षित रिसाइक्लिंग", "सुरक्षित रिसायकलिंग", "Safe Recycling"),
        "unusual_price_warn" to Trans("असामान्य मूल्य: यह हाल के बाज़ार भाव से काफी भिन्न है। कृपया पुष्टि करें।", "असामान्य किंमत: हा दर बाजारभावापेक्षा वेगळा आहे.", "Unusual Price: This transaction is significantly different from recent market prices. Please verify."),

        // User requested exact Home Page and Core Flow Keys
        "namaste_heading" to Trans("नमस्ते!", "नमस्ते!", "Namaste!"),
        "what_do_you_want_to_sell" to Trans("आप क्या बेचना चाहते हैं?", "तुम्ही काय विकू इच्छिता?", "What do you want to sell?"),
        "sell_now" to Trans("अभी बेचें", "आता विका", "Sell Now"),
        "sahayak_name" to Trans("सहायक", "सहाय्यक", "Sahayak"),
        "sell_by_speaking" to Trans("(बोलकर बेचें)", "(बोलून विका)", "(Sell by Speaking)"),
        "retry" to Trans("पुनः प्रयास", "पुन्हा प्रयत्न", "Retry"),
        "choose_role" to Trans("अपनी भूमिका चुनें", "तुमची भूमिका निवडा", "Choose Your Role"),
        "seller_collector_role" to Trans("विक्रेता / कबाड़ी", "विक्रेता / कबाडी", "Seller / Scrap Collector"),
        "seller_collector_desc" to Trans("ई-कचरा बेचें, लाइव रेट देखें और अधिकृत रिसाइक्लर्स से जुड़ें", "ई-कचरा विका, लाईव्ह दर पहा आणि अधिकृत रिसायकलर्सशी जोडा", "Sell e-waste, check live rates & connect with authorized recyclers"),
        "recycler_role" to Trans("अधिकृत रिसाइक्लर", "अधिकृत रिसायकलर", "Recycler"),
        "recycler_role_desc" to Trans("लॉट खरीदें, सामग्री सत्यापित करें और डिजिटल भुगतान करें", "लॉट खरेदी करा, साहित्य तपासा आणि डिजिटल पेमेंट करा", "Buy bulk lots, verify materials & make digital payouts"),
        "continue_btn" to Trans("आगे बढ़ें", "पुढे जा", "Continue"),
        "login_title" to Trans("लॉगिन / साइनअप", "लॉगिन / साइनअप", "Login / Signup"),
        "enter_phone_hint" to Trans("अपना मोबाइल नंबर दर्ज करें", "तुमचा मोबाईल नंबर टाका", "Enter your mobile number"),
        "phone_sub_disclaimer" to Trans("हम आपके नंबर पर 4 अंकों का OTP कोड भेजेंगे।", "आम्ही तुमच्या नंबरवर 4-अंकी OTP पाठवू.", "We will send an OTP verification code."),
        "terms_notice" to Trans("आगे बढ़कर, आप हमारे नियम व शर्तों और गोपनीयता नीति से सहमत होते हैं।", "पुढे जाऊन, आपण आमच्या अटी व शर्ती आणि गोपनीयता धोरणाशी सहमत आहात.", "By continuing, you agree to our Terms of Service and Privacy Policy."),
        "verify_otp_title" to Trans("ओटीपी सत्यापित करें", "ओटीपी पडताळणी करा", "Verify OTP"),
        "enter_otp_hint" to Trans("कोड दर्ज करें", "कोड टाका", "Enter Code"),
        "didnt_receive_otp" to Trans("कोड नहीं मिला?", "कोड मिळाला नाही?", "Didn't receive code?"),
        "resend_btn" to Trans("ओटीपी दोबारा भेजें", "ओटीपी पुन्हा पाठवा", "Resend OTP"),
        "verify_cta" to Trans("सत्यापित करें", "पडताळणी करा", "Verify"),
        "user_details_title" to Trans("आपकी जानकारी", "तुमची माहिती", "Your Details"),
        "first_name_hint" to Trans("पहला नाम", "पहिले नाव", "First Name"),
        "last_name_hint" to Trans("अंतिम नाम", "आडनाव", "Last Name"),
        "take_photo_title" to Trans("मटेरियल की फोटो लें", "मटेरियलचा फोटो घ्या", "Take Material Photo"),
        "take_photo_action" to Trans("फोटो खींचें", "फोटो काढा", "Take Photo"),
        "gallery_action" to Trans("गैलरी से चुनें", "गॅलरीतून निवडा", "Choose from Gallery"),
        "ai_categorizer_header" to Trans("AI मटेरियल कैटेगराइज़र", "AI मटेरियल वर्गीकरण", "AI Material Categorizer"),
        "works_offline_badge" to Trans("ऑफलाइन कार्य करता है ⚡", "ऑफलाइन कार्य करते ⚡", "Works Offline ⚡"),
        "detected_scrap_title" to Trans("पहचाना गया ई-कचरा प्रकार", "ओळखलेला ई-कचरा प्रकार", "Detected Scrap Type"),
        "confirm_category_cta" to Trans("श्रेणी की पुष्टि करें", "प्रकार निश्चित करा", "Confirm Category"),
        "price_trends_header" to Trans("मूल्य और बाज़ार रुझान", "किंमत आणि बाजार कल", "Price & Trends"),
        "material_quantity_lbl" to Trans("सामग्री और मात्रा", "साहित्य आणि प्रमाण", "Material & Quantity"),
        "estimated_price_lbl" to Trans("अनुमानित मूल्य", "अंदाजे मूल्य", "Estimated Price"),
        "local_price_trends_lbl" to Trans("इस लोकेशन के वास्तविक डेटा अनुसार मूल्य रुझान", "या लोकेशनच्या रिअल डेटा नुसार किंमतीचा कल", "Price Trends using Real Data of this Location"),
        "select_recycler_header" to Trans("रिसाइक्लर लॉट चुनें", "रिसायकलर लॉट निवडा", "Select Recycler Lot"),
        "choose_payment_method_title" to Trans("भुगतान का तरीका", "पेमेंट पद्धत", "Payment Method"),
        "payment_cash_lbl" to Trans("नकद (Cash on Delivery)", "रोख (Cash on Delivery)", "Cash on Delivery"),
        "payment_upi_lbl" to Trans("तुरंत यूपीआई (UPI / Digital)", "तातडीने यूपीआय (UPI / Digital)", "Instant UPI / Digital"),
        "lot_confirmed_header" to Trans("लॉट कन्फर्म हो गया!", "लॉट निश्चित झाला!", "Lot Confirmed!"),
        "lot_confirmed_sub" to Trans("आपका स्क्रैप लॉट सफलतापूर्वक पंजीकृत हो गया है।", "तुमचा स्क्रॅप लॉट यशस्वीरीत्या नोंदवला गेला आहे.", "Your scrap lot has been successfully registered."),
        "lot_id_label" to Trans("लॉट ID:", "लॉट ID:", "Lot ID:"),
        "view_in_history_btn" to Trans("इतिहास (History) में देखें", "इतिहास (History) मध्ये पहा", "View in History"),
        "home_bottom_nav" to Trans("होम", "मुख्य", "Home"),
        "rate_list_bottom_nav" to Trans("रेट लिस्ट", "दर यादी", "Rate list"),
        "sell_bottom_nav" to Trans("बेचें", "विका", "Sell"),
        "history_bottom_nav" to Trans("इतिहास", "इतिहास", "History"),
        "profile_bottom_nav" to Trans("प्रोफाइल", "प्रोफाइल", "Profile")
    )
}
